name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html
            # Check if git repo exists, if not clone it
            if [ ! -d .git ]; then
              cd /var/www
              rm -rf html
              git clone https://github.com/Immenz0260/aws-capstone-project-group-10.git html
              cd html
            else
              git pull origin main
            fi
            sudo systemctl restart nginx